Repository hnccbits/Website, pull requests merged in 2021-11, with the labels that each got.

#25 refactored some code and changed some styles
  components/button/Button.module.css
  components/footer/Footer.module.css
  components/gridGallery/GridGallery.js
  components/gridGallery/grid-gallery.module.css
  components/navbar/Navbar.js
  components/navbar/Navbar.module.css
  components/socialsbar/SocialsBar.module.css
  components/sponsors/Sponsors.js
  components/teams/Team.module.css
  components/teams/TeamCard.js
  components/video/Video.js
Labels: improvement

#24 Color schema changed to dark black
  components/socialsbar/SocialsBar.module.css
  styles/global.css
  tailwind.config.js
Labels: improvement

#28 Feat/tech stack
  components/associations/Associations.js
  components/associations/association.module.css
  components/navbar/Navbar.js
  components/navbar/Navbar.module.css
  components/sponsors/Sponsors.js
  components/techStack/TechStack.js
  components/techStack/tech-stack.module.css
  pages/about.js
  pages/index.js
  public/sponsors/association1.png
  public/sponsors/association2.jpg
  public/sponsors/association2.png
  public/sponsors/codechef.jpg
  public/sponsors/gdsc.png
  public/sponsors/gfg.png
  styles/global.css
Labels: bug, improvement

#31 #30 Added events section in the about page
  components/event/EventCard.js
  components/event/Events.js
  components/event/event.module.css
  lib/data/EventsData.js
  pages/about.js
  public/events/bitcode.jpg
  public/events/codestorm.jpg
  public/events/designatello.jpg
  public/events/doty.jpg
  public/events/hackatron-poster.jpeg
  public/events/hacktoberfest.jpg
  public/events/htober_final.jpg
  public/events/introtooops.jpg
  public/events/mlsession.jpg
  public/events/pythonforml.jpg
  public/events/speaker.jpg
  public/events/tmc.jpeg
  public/events/women-in-tech.jpg
Labels: enhancement, priority

#32 #4 Added social icons in the team card on teams page
  components/teams/Team.module.css
  components/teams/TeamCard.js
  lib/data/TeamData.js
  pages/teams.js
Labels: improvement
